import { defineConfig } from 'vitepress'

const SITE = 'https://yankeelanguage.vercel.app'
const OG_IMG = SITE + '/og-cover.svg'
const GH = 'https://github.com/NormikChel/YL'

const ylGrammar = {
  name: 'yl',
  scopeName: 'source.yl',
  patterns: [
    { include: '#keywords' }, { include: '#strings' },
    { include: '#comments' }, { include: '#numbers' },
    { include: '#operators' },
  ],
  repository: {
    keywords: { patterns: [{ name: 'keyword.control.yl', match: '[\u00A4\u00A7\u03BB\u00BB\u27E6\u27E7\u00BF\u21F6\u21A4\u2021\u22D4\u21E2\u2020\u26A1\u23F8\u2611\u2610\u2205\u203C\u2047\u2326\u2295\u27EA\u27EB\u2298\u21BB\u2261]' }] },
    strings: { patterns: [
      { name: 'string.quoted.double.yl', begin: '"', end: '"' },
      { name: 'string.quoted.single.yl', begin: "'", end: "'" },
    ]},
    comments: { patterns: [{ name: 'comment.line.tilde.yl', match: '~.*$' }] },
    numbers: { patterns: [{ name: 'constant.numeric.yl', match: '[0-9]+' }] },
    operators: { patterns: [{ name: 'keyword.operator.yl', match: '[-+*/%<>=!&|.]' }] },
  },
}

export default defineConfig({
  title: 'YL',
  description: 'Yankee Language - esoteric programming language on PHP with unicode syntax',
  cleanUrls: true,
  lang: 'ru',
  sitemap: { hostname: SITE, lastmodDateOnly: true },
  markdown: { languages: [ylGrammar] },
  head: [
    ['meta', { name: 'viewport', content: 'width=device-width, initial-scale=1.0, viewport-fit=cover' }],
    ['meta', { name: 'theme-color', content: '#a78bfa', media: '(prefers-color-scheme: light)' }],
    ['meta', { name: 'theme-color', content: '#0f0f17', media: '(prefers-color-scheme: dark)' }],
    ['link', { rel: 'icon', type: 'image/svg+xml', href: '/favicon.svg' }],
    ['link', { rel: 'apple-touch-icon', sizes: '180x180', href: '/apple-touch-icon.png' }],
    ['link', { rel: 'manifest', href: '/manifest.webmanifest' }],
    ['meta', { name: 'author', content: 'NormikChel' }],
    ['meta', { name: 'keywords', content: 'YL, Yankee Language, esoteric programming language, PHP, unicode syntax' }],
    ['meta', { name: 'robots', content: 'index, follow, max-image-preview:large' }],
    ['link', { rel: 'canonical', href: SITE + '/' }],
    ['link', { rel: 'alternate', hreflang: 'ru', href: SITE + '/' }],
    ['link', { rel: 'alternate', hreflang: 'en', href: SITE + '/en/' }],
    ['link', { rel: 'alternate', hreflang: 'zh-Hans', href: SITE + '/zh-Hans/' }],
    ['link', { rel: 'alternate', hreflang: 'zh-Hant', href: SITE + '/zh-Hant/' }],
    ['link', { rel: 'alternate', hreflang: 'x-default', href: SITE + '/' }],
    ['link', { rel: 'alternate', type: 'application/rss+xml', title: 'YL RSS', href: SITE + '/rss.xml' }],
    ['link', { rel: 'alternate', type: 'application/atom+xml', title: 'YL Atom', href: SITE + '/atom.xml' }],
    ['meta', { property: 'og:type', content: 'website' }],
    ['meta', { property: 'og:site_name', content: 'YL - Yankee Language' }],
    ['meta', { property: 'og:image', content: OG_IMG }],
    ['meta', { property: 'og:image:width', content: '1200' }],
    ['meta', { property: 'og:image:height', content: '630' }],
    ['meta', { name: 'twitter:card', content: 'summary_large_image' }],
    ['meta', { name: 'twitter:image', content: OG_IMG }],
    ['script', { type: 'application/ld+json' }, JSON.stringify({
      '@context': 'https://schema.org',
      '@graph': [
        { '@type': 'WebSite', '@id': SITE + '/#website', url: SITE + '/',
          name: 'YL - Yankee Language',
          inLanguage: ['ru', 'en', 'zh-Hans', 'zh-Hant'],
          publisher: { '@id': SITE + '/#person' } },
        { '@type': 'Person', '@id': SITE + '/#person', name: 'NormikChel',
          url: GH, sameAs: [GH] },
        { '@type': 'SoftwareApplication', '@id': SITE + '/#app', name: 'YL',
          alternateName: 'Yankee Language',
          applicationCategory: 'DeveloperApplication',
          operatingSystem: 'Cross-platform (PHP 8.1+)',
          programmingLanguage: ['PHP', 'Yankee'],
          license: 'https://opensource.org/licenses/MIT',
          offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
          codeRepository: GH, softwareVersion: '4.0.0',
          author: { '@id': SITE + '/#person' } },
      ],
    })],
  ],
  themeConfig: {
    logo: '/logo.svg',
    siteTitle: 'YL',
    socialLinks: [{ icon: 'github', link: GH }],
  },
  locales: {
    root: {
      label: 'Русский',
      lang: 'ru',
      title: 'YL — Yankee Language',
      description: 'Эзотерический язык программирования на PHP с юникод-синтаксисом',
      themeConfig: {
        nav: [
          { text: 'Руководство', link: '/guide/getting-started', activeMatch: '/guide/' },
          { text: 'Синтаксис', link: '/guide/syntax' },
          { text: 'Stdlib', link: '/guide/stdlib' },
          { text: 'Примеры', link: '/examples/' },
          { text: 'Playground', link: GH + '/tree/main/playground' },
        ],
        sidebar: {
          '/guide/': [{ text: 'Руководство', items: [
            { text: 'Быстрый старт', link: '/guide/getting-started' },
            { text: 'Синтаксис', link: '/guide/syntax' },
            { text: 'Стандартная библиотека', link: '/guide/stdlib' },
          ]}],
          '/examples/': [{ text: 'Примеры', items: [
            { text: 'Все примеры', link: '/examples/' },
            { text: 'ООП', link: '/examples/oop' },
            { text: 'Генераторы', link: '/examples/generators' },
            { text: 'Async', link: '/examples/async' },
          ]}],
        },
        outline: { label: 'На этой странице', level: [2, 3] },
        docFooter: { prev: 'Назад', next: 'Вперёд' },
        darkModeSwitchLabel: 'Тема',
        lightModeSwitchTitle: 'Светлая тема',
        darkModeSwitchTitle: 'Тёмная тема',
        sidebarMenuLabel: 'Меню',
        returnToTopLabel: 'Наверх',
        langMenuLabel: 'Сменить язык',
        externalLinkIcon: true,
        editLink: { pattern: GH + '/edit/main/docs/:path', text: 'Редактировать на GitHub' },
        lastUpdated: { text: 'Обновлено' },
        footer: {
          message: 'Сделано на PHP. Лицензия MIT.',
          copyright: '© 2026 YL Contributors',
        },
        notFound: {
          title: 'Страница не найдена',
          quote: 'Возможно, страница переехала или её никогда не было.',
          linkLabel: 'на главную',
          linkText: 'На главную',
        },
        search: {
          provider: 'local',
          options: {
            translations: {
              button: { buttonText: 'Поиск', buttonAriaLabel: 'Поиск' },
              modal: {
                displayDetails: 'Показать подробный список',
                resetButtonTitle: 'Сбросить',
                backButtonTitle: 'Закрыть поиск',
                noResultsText: 'Ничего не найдено',
                footer: {
                  selectText: 'выбрать',
                  selectKeyAriaLabel: 'Enter',
                  navigateText: 'перемещаться',
                  navigateUpKeyAriaLabel: 'Стрелка вверх',
                  navigateDownKeyAriaLabel: 'Стрелка вниз',
                  closeText: 'закрыть',
                  closeKeyAriaLabel: 'Esc',
                },
              },
            },
          },
        },
      },
    },
    en: {
      label: 'English',
      lang: 'en',
      link: '/en/',
      title: 'YL — Yankee Language',
      description: 'Esoteric programming language on PHP with unicode syntax',
      themeConfig: {
        nav: [
          { text: 'Guide', link: '/en/guide/getting-started', activeMatch: '/en/guide/' },
          { text: 'Syntax', link: '/en/guide/syntax' },
          { text: 'Stdlib', link: '/en/guide/stdlib' },
          { text: 'Examples', link: '/en/examples/' },
          { text: 'Playground', link: GH },
        ],
        sidebar: {
          '/en/guide/': [{ text: 'Guide', items: [
            { text: 'Getting started', link: '/en/guide/getting-started' },
            { text: 'Syntax', link: '/en/guide/syntax' },
            { text: 'Standard library', link: '/en/guide/stdlib' },
          ]}],
          '/en/examples/': [{ text: 'Examples', items: [
            { text: 'All examples', link: '/en/examples/' },
            { text: 'OOP', link: '/en/examples/oop' },
            { text: 'Generators', link: '/en/examples/generators' },
            { text: 'Async', link: '/en/examples/async' },
          ]}],
        },
        outline: { label: 'On this page', level: [2, 3] },
        docFooter: { prev: 'Previous', next: 'Next' },
        darkModeSwitchLabel: 'Appearance',
        lightModeSwitchTitle: 'Switch to light theme',
        darkModeSwitchTitle: 'Switch to dark theme',
        sidebarMenuLabel: 'Menu',
        returnToTopLabel: 'Return to top',
        langMenuLabel: 'Change language',
        editLink: { pattern: GH + '/edit/main/docs/:path', text: 'Edit this page on GitHub' },
        lastUpdated: { text: 'Updated' },
        footer: {
          message: 'Built on PHP. MIT License.',
          copyright: '© 2026 YL Contributors',
        },
        notFound: {
          title: 'Page not found',
          quote: 'This page may have moved, or it never existed.',
          linkLabel: 'go to home',
          linkText: 'Take me home',
        },
        search: {
          provider: 'local',
          options: {
            translations: {
              button: { buttonText: 'Search', buttonAriaLabel: 'Search' },
              modal: {
                displayDetails: 'Display detailed list',
                resetButtonTitle: 'Reset search',
                backButtonTitle: 'Close search',
                noResultsText: 'No results for',
                footer: {
                  selectText: 'to select',
                  selectKeyAriaLabel: 'Enter',
                  navigateText: 'to navigate',
                  navigateUpKeyAriaLabel: 'Arrow up',
                  navigateDownKeyAriaLabel: 'Arrow down',
                  closeText: 'to close',
                  closeKeyAriaLabel: 'Escape',
                },
              },
            },
          },
        },
      },
    },
    'zh-Hans': {
      label: '简体中文',
      lang: 'zh-Hans',
      link: '/zh-Hans/',
      title: 'YL — Yankee Language',
      description: '基于 PHP 的另类编程语言，使用 Unicode 符号作语法',
      themeConfig: {
        nav: [
          { text: '指南', link: '/zh-Hans/guide/getting-started', activeMatch: '/zh-Hans/guide/' },
          { text: '语法', link: '/zh-Hans/guide/syntax' },
          { text: '标准库', link: '/zh-Hans/guide/stdlib' },
          { text: '示例', link: '/zh-Hans/examples/' },
          { text: 'Playground', link: GH },
        ],
        sidebar: {
          '/zh-Hans/guide/': [{ text: '指南', items: [
            { text: '快速开始', link: '/zh-Hans/guide/getting-started' },
            { text: '语法', link: '/zh-Hans/guide/syntax' },
            { text: '标准库', link: '/zh-Hans/guide/stdlib' },
          ]}],
          '/zh-Hans/examples/': [{ text: '示例', items: [
            { text: '全部示例', link: '/zh-Hans/examples/' },
            { text: '面向对象', link: '/zh-Hans/examples/oop' },
            { text: '生成器', link: '/zh-Hans/examples/generators' },
            { text: '异步', link: '/zh-Hans/examples/async' },
          ]}],
        },
        outline: { label: '本页目录', level: [2, 3] },
        docFooter: { prev: '上一篇', next: '下一篇' },
        darkModeSwitchLabel: '主题',
        lightModeSwitchTitle: '切换到浅色主题',
        darkModeSwitchTitle: '切换到深色主题',
        sidebarMenuLabel: '菜单',
        returnToTopLabel: '回到顶部',
        langMenuLabel: '切换语言',
        editLink: { pattern: GH + '/edit/main/docs/:path', text: '在 GitHub 上编辑此页' },
        lastUpdated: { text: '最后更新' },
        footer: {
          message: '基于 PHP 构建。MIT 许可证。',
          copyright: '© 2026 YL Contributors',
        },
        notFound: {
          title: '页面未找到',
          quote: '该页面可能已移动，或者从未存在过。',
          linkLabel: '前往首页',
          linkText: '返回首页',
        },
        search: {
          provider: 'local',
          options: {
            translations: {
              button: { buttonText: '搜索', buttonAriaLabel: '搜索' },
              modal: {
                displayDetails: '显示详细列表',
                resetButtonTitle: '清除查询条件',
                backButtonTitle: '关闭搜索',
                noResultsText: '找不到结果',
                footer: {
                  selectText: '选择',
                  selectKeyAriaLabel: 'Enter',
                  navigateText: '切换',
                  navigateUpKeyAriaLabel: '上方向键',
                  navigateDownKeyAriaLabel: '下方向键',
                  closeText: '关闭',
                  closeKeyAriaLabel: 'Esc',
                },
              },
            },
          },
        },
      },
    },
    'zh-Hant': {
      label: '繁體中文（臺式）',
      lang: 'zh-Hant',
      link: '/zh-Hant/',
      title: 'YL — Yankee Language',
      description: '一個跑在 PHP 上面、語法全部用 Unicode 符號 der 冷門語言',
      themeConfig: {
        nav: [
          { text: '指南 der', link: '/zh-Hant/guide/getting-started', activeMatch: '/zh-Hant/guide/' },
          { text: '語法', link: '/zh-Hant/guide/syntax' },
          { text: '標準庫', link: '/zh-Hant/guide/stdlib' },
          { text: '範例', link: '/zh-Hant/examples/' },
          { text: 'Playground', link: GH },
        ],
        sidebar: {
          '/zh-Hant/guide/': [{ text: '指南', items: [
            { text: '立馬開始', link: '/zh-Hant/guide/getting-started' },
            { text: '語法 der', link: '/zh-Hant/guide/syntax' },
            { text: '標準庫', link: '/zh-Hant/guide/stdlib' },
          ]}],
          '/zh-Hant/examples/': [{ text: '範例', items: [
            { text: '全部範例', link: '/zh-Hant/examples/' },
            { text: '物件導向', link: '/zh-Hant/examples/oop' },
            { text: '生成器', link: '/zh-Hant/examples/generators' },
            { text: '非同步', link: '/zh-Hant/examples/async' },
          ]}],
        },
        outline: { label: '本頁有什麼', level: [2, 3] },
        docFooter: { prev: '上一個', next: '下一個' },
        darkModeSwitchLabel: '主題 der',
        lightModeSwitchTitle: '換成淺色',
        darkModeSwitchTitle: '換成深色，這比較帥',
        sidebarMenuLabel: '選單',
        returnToTopLabel: '衝回頂端',
        langMenuLabel: '換語言 der',
        editLink: { pattern: GH + '/edit/main/docs/:path', text: '去 GitHub 改這頁' },
        lastUpdated: { text: '更新於' },
        footer: {
          message: '用 PHP 寫 der。MIT 授權。',
          copyright: '© 2026 YL Contributors',
        },
        notFound: {
          title: '這頁母湯，找不到',
          quote: '可能搬走了，けどう也可能從來沒存在過 der。',
          linkLabel: '回首頁',
          linkText: '帶我回家',
        },
        search: {
          provider: 'local',
          options: {
            translations: {
              button: { buttonText: '找一下', buttonAriaLabel: '找東西' },
              modal: {
                displayDetails: '看詳細一點',
                resetButtonTitle: '清掉重來',
                backButtonTitle: '關掉',
                noResultsText: '找不到啦，母湯',
                footer: {
                  selectText: '選',
                  selectKeyAriaLabel: 'Enter',
                  navigateText: '上下切換',
                  navigateUpKeyAriaLabel: '往上',
                  navigateDownKeyAriaLabel: '往下',
                  closeText: '關掉',
                  closeKeyAriaLabel: 'Esc',
                },
              },
            },
          },
        },
      },
    },
  },
})